esphome:
  name: "master-bedroom-multi-sensor"
  friendly_name: Master Bedroom Multi-Sensor

  project:
    name: "Kerby-Tech.Multi-Sensor"
    version: "1.0.5"

esp32:
  variant: esp32c6
  flash_size: 4MB
  framework: 
    type: esp-idf

logger:

network:
  enable_ipv6: true

switch:
  - platform: restart
    name: "Reboot Sensor"
    icon: mdi:power-cycle

time:
  - platform: sntp
    id: "sntp_time"
    on_time:
      - minutes: /1
        then:
          - lvgl.label.update:
              id: time_value
              text:
                time_format: "%H:%M %p"

i2c:
  sda: GPIO6
  scl: GPIO7
  #scan: True
  low_power_mode: true

spi:
  clk_pin: GPIO0
  mosi_pin: GPIO1

sensor:
  - platform: sen6x
    type: SEN66
    pm_1_0:
      name: PM 1µm
      state_class: "measurement"
      unit_of_measurement: "μg/m³"
      id: pm_1_0
    pm_2_5:
      name: PM 2.5µm
      state_class: "measurement"
      unit_of_measurement: "μg/m³"
      id: pm_2_5
      on_value:
        - lvgl.arc.update:
            id: pm25_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: pm25_value
            text:
              format: "%.0f"
              args: [ x ]
              if_nan: "N/A"
    pm_4_0:
      name: PM 4µm
      state_class: "measurement"
      unit_of_measurement: "μg/m³"
      id: pm_4_0
    pm_10_0:
      name: PM 10µm
      state_class: "measurement"
      unit_of_measurement: "μg/m³"
      id: pm_10_0
      on_value:
        - lvgl.arc.update:
            id: pm10_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: pm10_value
            text:
              format: "%.0f"
              args: [ x ]
              if_nan: "N/A"
    temperature:
      name: Temperature
      state_class: "measurement"
      id: temperature
      on_value:
        - lvgl.arc.update:
            id: temperature_arc
            value: !lambda return x * (9.0/5.0) + 32.0;
        - lvgl.label.update:
            id: temperature_value
            text: 
              format: "%.0f°F"
              args: [ x * (9.0/5.0) + 32.0 ]
              if_nan: "N/A"
        - script.execute:
            id: set_arc_gradient
            widget_id: temperature_arc
            current_value: x
    humidity:
      name: Humidity
      state_class: "measurement"
      id: humidity
      on_value:
        - lvgl.arc.update:
            id: humidity_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: humidity_value
            text:
              format: "%.0f%%"
              args: [ x ]
              if_nan: "N/A"
    voc:
      name: VOC
      state_class: "measurement"
      unit_of_measurement: "VOC Index"
      id: voc
      on_value:
        - lvgl.arc.update:
            id: voc_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: voc_value
            text:
              format: "%.0f"
              args: [ x ]
              if_nan: "N/A"
    nox:
      name: NOx
      state_class: "measurement"
      unit_of_measurement: "NOx Index"
      id: nox
    co2:
      name: Carbon Dioxide
      state_class: "measurement"
      unit_of_measurement: "ppm"
      id: co2
      on_value:
        - lvgl.arc.update:
            id: co2_arc
            value: !lambda return x;
        - lvgl.label.update:
            id: co2_value
            text:
              format: "%.0f"
              args: [ x ]
              if_nan: "N/A"
    update_interval: 60s

font:
  - file: "gfonts://Roboto"
    id: roboto_icons
    size: 40
    extras:
      file: "gfonts://Noto+Emoji"
      glyphs: "🌡💧♨️" 
  - file: "gfonts://Roboto"
    id: roboto_time
    size: 32
    glyphsets: "GF_Latin_Kernel"
    glyphs: "₂³μ"

display:
  - platform: mipi_spi
    id: ST7789
    model: ST7789V
    data_rate: 1MHz
    enable_pin: 
      number: GPIO5
      ignore_strapping_warning: true
    cs_pin: 
      number: GPIO4
      ignore_strapping_warning: true
    dc_pin: GPIO3
    reset_pin: GPIO2
    dimensions:
      height: 320
      width: 170
      offset_width: 34
    invert_colors: true
    update_interval: never
    #lambda: |-
      #it.printf(0, 0, id(roboto_icons), Color(0xFF0000), COLOR_OFF, display::TextAlign::TOP_LEFT, "🌡");
      #it.printf(0, 45, id(roboto_icons), Color(0x0000FF), COLOR_OFF, display::TextAlign::TOP_LEFT, "💧");
      #it.printf(0, 95, id(roboto_time), Color(0xFFEB00), COLOR_OFF, display::TextAlign::TOP_LEFT, "CO₂");
      #it.printf(0, 135, id(roboto_icons), Color(0x00FF00), COLOR_OFF, display::TextAlign::TOP_LEFT, "♨️");
      #it.printf(0, 180, id(roboto_time), Color(0xc19a6b), COLOR_OFF, display::TextAlign::TOP_LEFT, "1.0");
      #it.printf(0, 225, id(roboto_time), Color(0xc19a6b), COLOR_OFF, display::TextAlign::TOP_LEFT, "2.5");
      #it.printf(0, 270, id(roboto_time), Color(0xc19a6b), COLOR_OFF, display::TextAlign::TOP_LEFT, "10");

      #it.printf(60, 0, id(roboto_icons), "%.0f°F", id(temperature).state * (9.0/5.0) + 32.0);
      #it.printf(60, 45, id(roboto_icons), "%.0f%%", id(humidity).state);
      #it.printf(60, 90, id(roboto_time), "%.0fppm", id(co2).state);
      #it.printf(60, 135, id(roboto_time), "%.0f", id(voc).state);
      #it.printf(60, 180, id(roboto_time), "%.0fμg/m³", id(pm_1_0).state);
      #it.printf(60, 225, id(roboto_time), "%.0fμg/m³", id(pm_2_5).state);
      #it.printf(60, 270, id(roboto_time), "%.0fμg/m³", id(pm_10_0).state);

script:
  - id: set_arc_gradient
    mode: parallel
    parameters:
      widget_id: string
      current_value: int
    then:
      - lambda: |-
          float min_value = lv_arc_get_min_value(widget_id, LV_PART_INDICATOR)
          float max_value = lv_arc_get_max_value(widget_id, LV_PART_INDICATOR)
          //Calculate where the current value is as a percentage of the range between mix and max value
          float gradient_percentage = (current_value - min_value) / (max_value - lower_value);
          Color start_color = Color(6, 73, 51); // Green
          Color end_color = Color(287, 6, 6);   // Red
          Color gradient_color = start_color.gradient(end_color, gradient_percentage);
          lv_obj_set_style_arc_color(widget_id, gradient_color, LV_PART_INDICATOR | LV_STATE_DEFAULT);
      #- lvgl.arc.update:
          #id: !lambda return widget_id;
          #arc_color: !lambda return gradient_color;
